#!/usr/bin/env python3
"""
Build a Meta Ads Manager bulk-import file from a structured YAML brief.

Inputs:
  brief.yml          A campaign / ad set / ads description. See examples/.
  scripts/spec.json  Generated by extract_columns.py from the bundled .xltx.

Outputs (in --out dir, default ./output):
  output.xlsx        Filled spreadsheet for human review (all 143 columns).
  output.txt         UTF-16 LE BOM, tab-separated, \\r\\n line endings.
                     This is the file you upload in Ads Manager.

Usage:
  python scripts/build_import.py brief.yml
  python scripts/build_import.py brief.yml --images ./images --out ./output
  python scripts/build_import.py brief.yml --check     # validate only

Hardcoded defaults baked in (override per-brief):
  - Country: AR, age range: 25-54, audience: broad
  - Placements: Advantage+ Auto (leave platform/position columns blank)
  - Budget mode: CBO (Campaign Daily Budget)
  - Bid strategy: Highest volume or value
  - Buying type: AUCTION
  - Status: PAUSED at every level
  - Special Ad Categories: none
  - Required image aspect ratios: 4:5 + 9:16 (script errors if either missing)
  - Default creative matrix: 3 titles x 3 bodies x 3 creatives = 27 ads
  - UTM tags: utm_source=facebook&utm_medium=paid_social&utm_campaign={CN}&utm_content={AN}
  - Optimization goal for Outcome Leads: CONVERSATIONS
  - Optimization goal for Outcome Sales: NO DEFAULT (must be in brief)
"""

from __future__ import annotations

import argparse
import codecs
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill

SKILL_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SPEC = SKILL_ROOT / "scripts" / "spec.json"

DEFAULTS = {
    "country": "AR",
    "age_min": 25,
    "age_max": 54,
    "buying_type": "AUCTION",
    "campaign_bid_strategy": "Highest volume or value",
    "ad_set_bid_strategy": "Highest volume or value",
    "campaign_status": "PAUSED",
    "ad_set_status": "PAUSED",
    "ad_status": "PAUSED",
    "special_ad_categories": "none",
    "utm_template": "utm_source=facebook&utm_medium=paid_social&utm_campaign={campaign_name}&utm_content={ad_name}",
    "required_aspect_ratios": ["4:5", "9:16"],
    "image_file_aspect_ratio": "4:5",
    "matrix_default_size": [3, 3, 3],
    "ads_per_adset_cap_when_no_matrix": 5,
    "optimization_goal_by_objective": {
        "Outcome Leads": "CONVERSATIONS",
        "Outcome Sales": None,
        "Outcome Awareness": None,
        "Outcome Engagement": None,
        "Outcome Traffic": None,
        "App Promotion": None,
    },
}

LIMITS = {
    "name_max": 35,
    "title_max": 40,
    "title_warn": 27,
    "body_max": 2200,
    "body_warn": 125,
    "description_max": 200,
    "description_warn": 30,
    "import_file_max_bytes": 2_000_000,
}

DATE_RE = re.compile(r"^\d{2}/\d{2}/\d{2} \d{2}:\d{2}$")
CURRENCY_RE = re.compile(r"^\d+(\.\d{1,2})?$")
NARROW_TARGETING_KEYS = {
    "custom_audiences",
    "lookalike_audiences",
    "excluded_custom_audiences",
    "zip",
    "cities",
    "regions",
}


@dataclass
class BuildIssue:
    severity: str
    message: str
    row: int | None = None
    column: str | None = None

    def __str__(self) -> str:
        loc = []
        if self.row is not None:
            loc.append(f"row {self.row}")
        if self.column:
            loc.append(f'col "{self.column}"')
        prefix = f"[{self.severity.upper()}]"
        if loc:
            prefix += " " + ", ".join(loc)
        return f"{prefix} {self.message}"


@dataclass
class BuildReport:
    issues: list[BuildIssue] = field(default_factory=list)

    def error(self, msg: str, row: int | None = None, column: str | None = None) -> None:
        self.issues.append(BuildIssue("error", msg, row, column))

    def warn(self, msg: str, row: int | None = None, column: str | None = None) -> None:
        self.issues.append(BuildIssue("warning", msg, row, column))

    @property
    def errors(self) -> list[BuildIssue]:
        return [i for i in self.issues if i.severity == "error"]

    @property
    def warnings(self) -> list[BuildIssue]:
        return [i for i in self.issues if i.severity == "warning"]


def load_spec(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def load_brief(path: Path) -> dict:
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def expand_matrix(matrix: dict, creatives_index: dict[str, dict]) -> list[dict]:
    titles = matrix.get("titles") or []
    bodies = matrix.get("bodies") or []
    creative_ids = matrix.get("creative_ids") or list(creatives_index.keys())
    link = matrix.get("link")
    cta = matrix.get("cta")
    description = matrix.get("description")
    url_tags = matrix.get("url_tags")

    ads: list[dict] = []
    for ti, title in enumerate(titles, start=1):
        for bi, body in enumerate(bodies, start=1):
            for ci, cid in enumerate(creative_ids, start=1):
                creative = creatives_index.get(cid, {})
                ads.append(
                    {
                        "name": f"T{ti}_B{bi}_C{ci}_{cid}",
                        "title": title,
                        "body": body,
                        "creative_id": cid,
                        "creative": creative,
                        "link": link,
                        "cta": cta,
                        "link_description": description,
                        "url_tags": url_tags,
                    }
                )
    return ads


def truncate_name(name: str, max_chars: int = LIMITS["name_max"]) -> str:
    if len(name) <= max_chars:
        return name
    return name[: max_chars - 3] + "..."


def fill_utm(template: str, *, campaign_name: str, ad_name: str) -> str:
    return template.format(campaign_name=campaign_name, ad_name=ad_name)


def resolve_optimization_goal(objective: str, override: str | None) -> str | None:
    if override:
        return override
    return DEFAULTS["optimization_goal_by_objective"].get(objective)


def make_row(spec_columns: list[dict]) -> dict[str, Any]:
    return {col["name"]: "" for col in spec_columns}


def build_rows(brief: dict, spec: dict, report: BuildReport) -> list[dict]:
    spec_columns = spec["columns"]
    column_names = {col["name"] for col in spec_columns}

    creatives_input = brief.get("creatives") or []
    creatives_index: dict[str, dict] = {c["id"]: c for c in creatives_input}

    if not brief.get("campaigns"):
        report.error("Brief contains no campaigns")
        return []

    rows: list[dict] = []

    for camp in brief["campaigns"]:
        camp_name = camp.get("name")
        if not camp_name:
            report.error("Campaign missing 'name'")
            continue
        if len(camp_name) > LIMITS["name_max"]:
            report.error(
                f"Campaign name '{camp_name}' is {len(camp_name)} chars (max {LIMITS['name_max']})"
            )

        objective = camp.get("objective")
        if not objective:
            report.error(f"Campaign '{camp_name}' missing 'objective'")
            continue

        special_cat = camp.get("special_ad_categories", DEFAULTS["special_ad_categories"])
        special_cat_country = camp.get("special_ad_category_country", "")

        ad_sets = camp.get("ad_sets") or []
        if not ad_sets:
            report.error(f"Campaign '{camp_name}' has no ad_sets")
            continue

        for adset in ad_sets:
            adset_name = adset.get("name")
            if not adset_name:
                report.error(f"Campaign '{camp_name}' has ad_set without 'name'")
                continue
            if len(adset_name) > LIMITS["name_max"]:
                report.error(
                    f"Ad set name '{adset_name}' is {len(adset_name)} chars (max {LIMITS['name_max']})"
                )

            opt_goal_override = adset.get("optimization_goal")
            opt_goal = resolve_optimization_goal(objective, opt_goal_override)
            if opt_goal is None:
                report.error(
                    f"Campaign '{camp_name}': objective '{objective}' has no default "
                    f"optimization_goal; ad_set '{adset_name}' must specify one in the brief"
                )

            country = adset.get("country", DEFAULTS["country"])
            age_min = adset.get("age_min", DEFAULTS["age_min"])
            age_max = adset.get("age_max", DEFAULTS["age_max"])
            gender = adset.get("gender", "")
            custom_audiences = adset.get("custom_audiences", "")
            lookalike_audiences = adset.get("lookalike_audiences", "")

            if special_cat and special_cat != "none":
                dropped = []
                if custom_audiences:
                    dropped.append("custom_audiences")
                    custom_audiences = ""
                if lookalike_audiences:
                    dropped.append("lookalike_audiences")
                    lookalike_audiences = ""
                if age_min and age_min < 18:
                    dropped.append(f"age_min<18 (was {age_min})")
                    age_min = 18
                if dropped:
                    report.warn(
                        f"Ad set '{adset_name}' has Special Ad Category '{special_cat}'; "
                        f"dropped incompatible targeting: {', '.join(dropped)}"
                    )

            ads_for_set: list[dict]
            if "creative_matrix" in adset:
                ads_for_set = expand_matrix(adset["creative_matrix"], creatives_index)
                if not ads_for_set:
                    report.error(
                        f"Ad set '{adset_name}': creative_matrix expanded to 0 ads "
                        "(empty titles/bodies/creative_ids?)"
                    )
                    continue
            elif "ads" in adset:
                ads_for_set = []
                for ad in adset["ads"]:
                    cid = ad.get("creative_id")
                    creative = creatives_index.get(cid, {}) if cid else {}
                    ads_for_set.append({**ad, "creative": creative})
                cap = DEFAULTS["ads_per_adset_cap_when_no_matrix"]
                if len(ads_for_set) > cap:
                    report.error(
                        f"Ad set '{adset_name}' has {len(ads_for_set)} discrete ads "
                        f"(max {cap} when no creative_matrix is used)"
                    )
            else:
                report.error(f"Ad set '{adset_name}' has neither 'ads' nor 'creative_matrix'")
                continue

            for ad in ads_for_set:
                row = make_row(spec_columns)

                row["Campaign Name"] = camp_name
                row["Campaign Status"] = camp.get("status", DEFAULTS["campaign_status"])
                row["Special Ad Categories"] = special_cat
                if special_cat_country:
                    row["Special Ad Category Country"] = special_cat_country
                row["Campaign Objective"] = objective
                row["Buying Type"] = camp.get("buying_type", DEFAULTS["buying_type"])
                if "daily_budget" in camp:
                    row["Campaign Daily Budget"] = camp["daily_budget"]
                if "lifetime_budget" in camp:
                    row["Campaign Lifetime Budget"] = camp["lifetime_budget"]
                if "spend_limit" in camp:
                    row["Campaign Spend Limit"] = camp["spend_limit"]
                row["Campaign Bid Strategy"] = camp.get(
                    "bid_strategy", DEFAULTS["campaign_bid_strategy"]
                )
                if "tags" in camp:
                    row["Tags"] = camp["tags"]
                if "start_time" in camp:
                    row["Campaign Start Time"] = camp["start_time"]
                if "stop_time" in camp:
                    row["Campaign Stop Time"] = camp["stop_time"]

                row["Ad Set Name"] = adset_name
                row["Ad Set Run Status"] = adset.get("status", DEFAULTS["ad_set_status"])
                if "daily_budget" in adset:
                    row["Ad Set Daily Budget"] = adset["daily_budget"]
                if "lifetime_budget" in adset:
                    row["Ad Set Lifetime Budget"] = adset["lifetime_budget"]
                if "start_time" in adset:
                    row["Ad Set Time Start"] = adset["start_time"]
                if "stop_time" in adset:
                    row["Ad Set Time Stop"] = adset["stop_time"]
                row["Countries"] = country
                row["Age Min"] = age_min
                row["Age Max"] = age_max
                if gender:
                    row["Gender"] = gender
                if custom_audiences:
                    row["Custom Audiences"] = custom_audiences
                if opt_goal:
                    row["Optimization Goal"] = opt_goal
                if "billing_event" in adset:
                    row["Billing Event"] = adset["billing_event"]
                if "bid_amount" in adset:
                    row["Bid Amount"] = adset["bid_amount"]
                if "bid_strategy" in adset:
                    row["Ad Set Bid Strategy"] = adset["bid_strategy"]
                page_id = adset.get("page_id") or brief.get("account", {}).get("page_id")
                if page_id:
                    row["Link Object ID"] = page_id

                ad_name = ad.get("name", "")
                if not ad_name:
                    report.error(f"Ad in set '{adset_name}' missing 'name'")
                    continue
                ad_name = truncate_name(ad_name)
                row["Ad Name"] = ad_name
                row["Ad Status"] = ad.get("status", DEFAULTS["ad_status"])

                title = ad.get("title", "")
                body = ad.get("body", "")
                row["Title"] = title
                row["Body"] = body
                if ad.get("link_description"):
                    row["Link Description"] = ad["link_description"]
                if ad.get("link"):
                    row["Link"] = ad["link"]
                if ad.get("display_link"):
                    row["Display Link"] = ad["display_link"]
                if ad.get("cta"):
                    row["Call to Action"] = ad["cta"]
                if ad.get("creative_type"):
                    row["Creative Type"] = ad["creative_type"]

                creative = ad.get("creative") or {}
                files = creative.get("files") if isinstance(creative, dict) else None
                if files:
                    primary_ratio = DEFAULTS["image_file_aspect_ratio"]
                    primary_file = files.get(primary_ratio)
                    if primary_file:
                        row["Image File Name"] = primary_file
                elif ad.get("image_file_name"):
                    row["Image File Name"] = ad["image_file_name"]
                if ad.get("image_hash"):
                    row["Image Hash"] = ad["image_hash"]
                if ad.get("story_id"):
                    row["Story ID"] = ad["story_id"]

                url_tags = ad.get("url_tags")
                if not url_tags:
                    url_tags = fill_utm(
                        DEFAULTS["utm_template"],
                        campaign_name=camp_name,
                        ad_name=ad_name,
                    )
                row["URL Tags"] = url_tags

                rows.append(row)

    return rows


def validate_rows(rows: list[dict], spec: dict, report: BuildReport) -> None:
    enum_by_column = {
        col["name"]: col["valid_values"] for col in spec["columns"] if "valid_values" in col
    }

    for i, row in enumerate(rows, start=2):
        ad_name = row.get("Ad Name", f"row {i}")

        title = row.get("Title", "")
        if title:
            if len(title) > LIMITS["title_max"]:
                report.error(
                    f"Title '{title}' is {len(title)} chars (max {LIMITS['title_max']})",
                    row=i,
                    column="Title",
                )
            elif len(title) > LIMITS["title_warn"]:
                report.warn(
                    f"Title '{title}' is {len(title)} chars (truncates on mobile Feed at "
                    f"{LIMITS['title_warn']})",
                    row=i,
                    column="Title",
                )

        body = row.get("Body", "")
        if body:
            if len(body) > LIMITS["body_max"]:
                report.error(
                    f"Body is {len(body)} chars (max {LIMITS['body_max']})",
                    row=i,
                    column="Body",
                )
            elif len(body) > LIMITS["body_warn"]:
                report.warn(
                    f"Body is {len(body)} chars (truncates with 'See more' at "
                    f"{LIMITS['body_warn']})",
                    row=i,
                    column="Body",
                )

        link_description = row.get("Link Description", "")
        if link_description:
            if len(link_description) > LIMITS["description_max"]:
                report.error(
                    f"Link Description is {len(link_description)} chars (max "
                    f"{LIMITS['description_max']})",
                    row=i,
                    column="Link Description",
                )
            elif len(link_description) > LIMITS["description_warn"]:
                report.warn(
                    f"Link Description is {len(link_description)} chars (often "
                    f"truncates at {LIMITS['description_warn']})",
                    row=i,
                    column="Link Description",
                )

        for col_name, valid_values in enum_by_column.items():
            value = row.get(col_name, "")
            if value == "" or value is None:
                continue
            if str(value) not in valid_values:
                report.error(
                    f"Value '{value}' is not in allowed enum {valid_values[:5]}"
                    + (" …" if len(valid_values) > 5 else ""),
                    row=i,
                    column=col_name,
                )

        for col_name in (
            "Campaign Daily Budget",
            "Campaign Lifetime Budget",
            "Campaign Spend Limit",
            "Ad Set Daily Budget",
            "Ad Set Lifetime Budget",
            "Bid Amount",
            "Ad Set Minimum Spend Limit",
            "Ad Set Maximum Spend Limit",
        ):
            v = row.get(col_name, "")
            if v == "" or v is None:
                continue
            try:
                fv = float(v)
                if fv < 0:
                    raise ValueError
                rounded = round(fv, 2)
                if abs(fv - rounded) > 1e-9:
                    raise ValueError
                row[col_name] = rounded
            except (TypeError, ValueError):
                report.error(
                    f"'{v}' is not a valid currency value (number with up to 2 decimals)",
                    row=i,
                    column=col_name,
                )

        for col_name in (
            "Campaign Start Time",
            "Campaign Stop Time",
            "Ad Set Time Start",
            "Ad Set Time Stop",
        ):
            v = row.get(col_name, "")
            if v == "" or v is None:
                continue
            if not DATE_RE.match(str(v)):
                report.error(
                    f"'{v}' is not in MM/DD/YY HH:MM format",
                    row=i,
                    column=col_name,
                )

        camp_status = str(row.get("Campaign Status", "")).upper()
        adset_status = str(row.get("Ad Set Run Status", "")).upper()
        ad_status = str(row.get("Ad Status", "")).upper()
        if ad_status == "ACTIVE" and adset_status and adset_status != "ACTIVE":
            report.warn(
                f"Ad '{ad_name}' is ACTIVE but ad set is {adset_status} — ad will not run",
                row=i,
            )
        if adset_status == "ACTIVE" and camp_status and camp_status != "ACTIVE":
            report.warn(
                f"Ad set is ACTIVE but campaign is {camp_status} — ad set will not run",
                row=i,
            )


def validate_images(rows: list[dict], images_dir: Path | None, report: BuildReport, brief: dict) -> None:
    if images_dir is None:
        return
    if not images_dir.is_dir():
        report.error(f"--images path is not a directory: {images_dir}")
        return

    available = {p.name: p for p in images_dir.iterdir() if p.is_file()}
    available_lower = {name.lower(): name for name in available}

    referenced_primary: set[str] = set()
    creatives_index = {c["id"]: c for c in (brief.get("creatives") or [])}
    for cid, c in creatives_index.items():
        files = c.get("files") or {}
        for ratio in DEFAULTS["required_aspect_ratios"]:
            fname = files.get(ratio)
            if not fname:
                report.error(
                    f"Creative '{cid}' is missing required aspect ratio '{ratio}' "
                    "(every creative must declare files for 4:5 and 9:16)"
                )
                continue
            if fname not in available:
                if fname.lower() in available_lower:
                    report.error(
                        f"Creative '{cid}' image '{fname}' not found at exact case in {images_dir} "
                        f"(found case-insensitive match '{available_lower[fname.lower()]}' — "
                        "Meta requires exact case)"
                    )
                else:
                    report.error(
                        f"Creative '{cid}' image '{fname}' not found in {images_dir}"
                    )

    for i, row in enumerate(rows, start=2):
        fname = row.get("Image File Name")
        if not fname:
            continue
        referenced_primary.add(fname)
        if fname not in available:
            if fname.lower() in available_lower:
                report.error(
                    f"Image '{fname}' not found at exact case in {images_dir}",
                    row=i,
                    column="Image File Name",
                )
            else:
                report.error(
                    f"Image '{fname}' not found in {images_dir}",
                    row=i,
                    column="Image File Name",
                )

    declared = set()
    for c in creatives_index.values():
        for fname in (c.get("files") or {}).values():
            declared.add(fname)
    stragglers = set(available.keys()) - declared - referenced_primary
    if stragglers:
        report.warn(
            f"{len(stragglers)} file(s) in {images_dir} not referenced by any creative: "
            + ", ".join(sorted(stragglers)[:5])
            + (" …" if len(stragglers) > 5 else "")
        )


def write_xlsx(rows: list[dict], spec: dict, out_path: Path) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = spec["sheet_name"]

    column_names = [col["name"] for col in spec["columns"]]
    ws.append(column_names)
    header_font = Font(bold=True)
    header_fill = PatternFill("solid", fgColor="DDDDDD")
    for cell in ws[1]:
        cell.font = header_font
        cell.fill = header_fill

    ws.freeze_panes = "A2"

    for row in rows:
        ws.append([row.get(name, "") for name in column_names])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(out_path)


def write_unicode_txt(rows: list[dict], spec: dict, out_path: Path) -> None:
    column_names = [col["name"] for col in spec["columns"]]
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with out_path.open("wb") as f:
        f.write(codecs.BOM_UTF16_LE)
        header_line = "\t".join(column_names) + "\r\n"
        f.write(header_line.encode("utf-16-le"))
        for row in rows:
            cells = [str(row.get(name, "")) if row.get(name, "") != "" else "" for name in column_names]
            line = "\t".join(cells) + "\r\n"
            f.write(line.encode("utf-16-le"))


def print_report(report: BuildReport) -> None:
    if report.warnings:
        print(f"\n{len(report.warnings)} warning(s):")
        for w in report.warnings:
            print(f"  {w}")
    if report.errors:
        print(f"\n{len(report.errors)} error(s):")
        for e in report.errors:
            print(f"  {e}")
    if not report.issues:
        print("No issues.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build Meta Ads bulk-import file from a YAML brief")
    parser.add_argument("brief", type=Path, help="Path to brief.yml")
    parser.add_argument("--out", type=Path, default=Path("./output"), help="Output directory")
    parser.add_argument("--images", type=Path, default=None, help="Directory with image files")
    parser.add_argument("--check", action="store_true", help="Validate only, do not write outputs")
    parser.add_argument("--spec", type=Path, default=DEFAULT_SPEC, help="Path to spec.json")
    args = parser.parse_args()

    if not args.brief.exists():
        print(f"Brief not found: {args.brief}", file=sys.stderr)
        return 2

    spec = load_spec(args.spec)
    brief = load_brief(args.brief)
    report = BuildReport()

    rows = build_rows(brief, spec, report)
    validate_rows(rows, spec, report)
    validate_images(rows, args.images, report, brief)

    print(f"Built {len(rows)} ad row(s) across {sum(len(c.get('ad_sets', [])) for c in brief.get('campaigns', []))} ad set(s) and {len(brief.get('campaigns', []))} campaign(s).")
    print_report(report)

    if report.errors:
        print("\nBuild failed due to errors above.", file=sys.stderr)
        return 1

    if args.check:
        print("\n--check passed.")
        return 0

    xlsx_path = args.out / "output.xlsx"
    txt_path = args.out / "output.txt"
    write_xlsx(rows, spec, xlsx_path)
    write_unicode_txt(rows, spec, txt_path)

    txt_size = txt_path.stat().st_size
    print(f"\nWrote {xlsx_path} ({len(rows)} rows)")
    print(f"Wrote {txt_path} ({txt_size:,} bytes)")
    if txt_size > LIMITS["import_file_max_bytes"]:
        print(
            f"WARNING: output.txt exceeds Meta's ~{LIMITS['import_file_max_bytes']:,} byte "
            "limit. Split into smaller batches.",
            file=sys.stderr,
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
